name = "remix"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"
scopes = [
    "write_products",
    "read_products",
    "write_collections",
    "read_collections",
    "read_orders",
    "write_orders",
    "read_inventory",
    "write_inventory",
    "read_discounts",
    "write_discounts"
]

[commands]
dev = "npm exec remix vite:dev"
