# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "your_client_id"
application_url = "your_app_url"
embedded = true
name = "red-devil-essentials"
handle = "red-devil-essentials"

[webhooks]
api_version = "2024-01"

[webhooks.privacy_compliance]
customer_deletion_url = "/webhooks/customers/redact"
shop_deletion_url = "/webhooks/shop/redact"
customer_data_request_url = "/webhooks/customers/data_request"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Core app functionality
scopes = [
  "read_products",
  "write_products",
  "read_product_listings",
  "write_product_listings",
  "read_inventory",
  "write_inventory",
  "read_price_rules",
  "write_price_rules",
  "read_discounts",
  "write_discounts",
  "read_scheduled_products",
  "write_scheduled_products"
]

[auth]
redirect_urls = [
  "https://your-app-url.com/auth/callback",
  "https://your-app-url.com/auth/shopify/callback"
]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true
