# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "97311f9ca9f17b392285ec80cb148a74"
application_url = "https://example.com/"
embedded = true
name = "Red Devil Essentials - Dev-V1"
handle = "red-devil-essentials-1"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "cron/15_min" ]
  uri = "/webhooks/scheduler"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[pos]
embedded = false

[build]
include_config_on_deploy = true
